### ISSUE TITLE
Default TinyMCE config

### ISSUE THREAD

**Issue by pxlrbt** [emilianotisato/nova-tinymce#21]
Hey, a possibility to set the default TinyMCE configuration would be nice!

**Comment by emilianotisato** [comment]
If you do not pass anything it already has a sensible default, did you try
it??

**Comment by pxlrbt** [comment]
Sorry, for the misleading explanation. It would be nice, if there was a possibility to overwrite this default to a different default.

**Comment by emilianotisato** [comment]
Ok, you mean you have many resources in your project or many textarea
fields in one resource in where you want a default that is different to the
default in the package??

In that case, you can for example have a property in you main
App/Nova/Resource.php file, something like this:

```
public $defaultTinyMceConf = [//... Your custom config array];
```
Then in every field you pass that options with `$this->$defaultTinyMceConf`

This is temporary, you can submit a PR and put the default in the config
file of the package so that can be published and override on demand?

Regards

**Comment by pxlrbt** [comment]
> Ok, you mean you have many resources in your project or many textarea
fields in one resource in where you want a default that is different to the
default in the package??

Yep. You got me right.

> In that case, you can for example have a property in you main
App/Nova/Resource.php file

That sounds like a good temporary solution. Did not think about it. Thanks.

> This is temporary, you can submit a PR and put the default in the config
file of the package so that can be published and override on demand?

I thought about something like a configuration file, so everybody can adjust the defaults to their needs. Maybe I can open a PR for that next week.

**Comment by rubenestevao** [comment]
I @emilianotisato 

I made a pull request that closes this issue.  Please check #24
