### ISSUE TITLE
Link button on the toolbar doesn't show

### ISSUE THREAD

**Issue by abishekrsrikaanth** [emilianotisato/nova-tinymce#42]
@emilianotisato I have the following code as mentioned in the example

```
NovaTinyMCE::make('body')->options([
                'plugins' => [
                    'lists preview hr anchor pagebreak image wordcount fullscreen directionality paste textpattern'
                ],
                'toolbar' => 'undo redo | styleselect | bold italic forecolor backcolor | alignleft aligncenter alignright alignjustify | image | bullist numlist outdent indent | link'
            ]),
```

<img width="935" alt="CleanShot 2020-09-15 at 18 57 08@2x" src="https://user-images.githubusercontent.com/1639302/93216381-49421500-f785-11ea-82d9-7afb0d8e54ae.png">

<img width="490" alt="CleanShot 2020-09-15 at 18 57 43@2x" src="https://user-images.githubusercontent.com/1639302/93216447-5bbc4e80-f785-11ea-93d0-e79072550566.png">

but for some reason, the button to add a link doesn't show on the toolbar or the menu. 
The `link` on the toolbar is supposed to add the button if I am right.
Any idea what may be the issue?

**Comment by emilianotisato** [comment]
Hello @abishekrsrikaanth ,
We are wrapping the tinymce javascript sdk directly, so any use case you can find it on the official website as instructed in the readme.

I think in your case the problem is you need to include the `link` also in the plugins array.
Toolbar is a "presentation layer" but if the plugin is not present it has nothing to present...

Let me know if that works...
