### ISSUE TITLE
Not working with whitecube / nova-flexible-content 

### ISSUE THREAD

**Issue by JonathanDoelan** [emilianotisato/nova-tinymce#54]
Is there something you can do to solve this issue?
[https://github.com/whitecube/nova-flexible-content/issues/156](https://github.com/whitecube/nova-flexible-content/issues/156)

The problem:
if you move components of `nova-flexible-content` up/down the content of `nova-tinymce` disappears and is not editable anymore. This is so anoying. I use it in production and my client is really upset about this.

So maybe you can help or anlyze the problem?

**Comment by emilianotisato** [comment]
Hello Jonathan, sorry you are frustrated about this issue. 

As described in the linked issue 156 in whitecube package, the problem is that the javascript library tinymce needs to initialize on page render, and we have no way to know if other packege or tool has cut the DOM for the editor and re positioned on other part of the DOM.

I have not much time now the attempt a solution on our end that can comply with this and any other feature scenario.

If you find one, feel free to send a PR and I gladly review it...
